# Lecture 3

In [1]:
%run set_env.py
%matplotlib inline

Check versions:
  numpy version     :'2.0.2'
  matplotlib version:'3.9.4'


## Indexing and Slicing

### 1D Array

Exactly as in regular python (<font color="green"><b>Nihil novi sub sole!</b></font>):
* Index: zero-based (like C++, whereas Fortran and R start at 1)<br>
  [Why numbering should start at zero (Edsger Wybe Dijkstra)](https://www.cs.utexas.edu/~EWD/ewd08xx/EWD831.PDF)
* [start:end:step) i.e. half-open interval
   * start: (default:0)
   * end: (default: all the way to the end (but exclusive of the last))
   * step: (default: +1)
* We can use negative indices:
   * -1: last el., etc.
* a[i]   : **indexing** (a copy) vs. <br> 
  a[j:m] : **slicing** (a view)

In [12]:
import numpy as np
# 1D Example
a = np.arange(21)

print(f"a := np.arange(21) :\n  a         :  {a}")
print(f"  a[4]      :  {a[4]}")
print(f"  a[:]      :  {a[:]}")
print(f"  a[5:]     :  {a[5:]}")
print(f"  a[2:12:3] :  {a[2:12:3]}")
print(f"  a[2::5]   :  {a[2::5]}") #start at 2, go all the way to the end, and stepsize of 5
print(f"  a[-5:-1]  :  {a[-5:-1]}") #-1 is the last element, -5 is the 5th last element. 
print(f"  a[-3:3:-1]:  {a[-3:3:-1]}")
print(f"  a[-7::2]  :  {a[-7::2]}")

#for 2 dimensions
print(f"  a[0]      :  {a[0]}")     # indexing -> ELement.   => LOWER rank
print(f"  a[0:1]    :  {a[0:1]}")   # slicing  -> ARRAY => preserve rank

a := np.arange(21) :
  a         :  [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
  a[4]      :  4
  a[:]      :  [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
  a[5:]     :  [ 5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
  a[2:12:3] :  [ 2  5  8 11]
  a[2::5]   :  [ 2  7 12 17]
  a[-5:-1]  :  [16 17 18 19]
  a[-3:3:-1]:  [18 17 16 15 14 13 12 11 10  9  8  7  6  5  4]
  a[-7::2]  :  [14 16 18 20]
  a[0]      :  0
  a[0:1]    :  [0]


### nD (2D, 3D, etc) Array

* Indexing & slicing are quite similar as for regular Python
* <font color="red"><b>MAIN DIFFERENCE</b></font>: 
  * [i][j] (Python) 
  * becomes [i,j] (NumPy)
 

In [6]:
# Example
print("  NUMPY::") #all dimensions are treated the same
x = np.array([3**i for i in range(8)]).reshape(2,4)
print(f"  x:\n{x}\n")
print(f"  x[0,0] :{x[0,0]}")
print(f"  x[1,2] :{x[1,2]}")
print(f"  x[1,:] :{x[1,:]}")
print(f"  x[1]   :{x[1]}")
print(f"  x[:,-1]:{x[:,-1]}\n") #every index on the same level, so -1 is 27 of row 0 and 2187 of row 1

print("  REGULAR PYTHON::")
x = x.tolist()
print(f"  x:\n{x}\n")
print(f"  x[0][0] :{x[0][0]}")
print(f"  x[1][2] :{x[1][2]}")
print(f"  x[1][:] :{x[1][:]}") 
print(f"  x[1]    :{x[1]}")
print(f"  x[:][-1]:{x[:][-1]}")       # SEEMINGLY WRONG RESULT!!!! What's going on?

  NUMPY::
  x:
[[   1    3    9   27]
 [  81  243  729 2187]]

  x[0,0] :1
  x[1,2] :729
  x[1,:] :[  81  243  729 2187]
  x[1]   :[  81  243  729 2187]
  x[:,-1]:[  27 2187]

  REGULAR PYTHON::
  x:
[[1, 3, 9, 27], [81, 243, 729, 2187]]

  x[0][0] :1
  x[1][2] :729
  x[1][:] :[81, 243, 729, 2187]
  x[1]    :[81, 243, 729, 2187]
  x[:][-1]:[81, 243, 729, 2187]


In [9]:
# Explanation (i.e. Under the Hood)
print(f"  x[:]   : {x[:]}")
print(f"  len(x) : {len(x)}")
y = x[:]
print(f"  y[-1]  : {y[-1]}")

# THEREFORE:
res =[ item[-1] for item in y]
print(f"  res    : {res}")

  x[:]   : [[1, 3, 9, 27], [81, 243, 729, 2187]]
  len(x) : 2
  y[-1]  : [81, 243, 729, 2187]
  res    : [27, 2187]


<font color="green"><b>NOTE: Numpy slicing has some additional features:</b></font><br>
 * if #indices < #dim: Assumes ALL of the remaining dimensions
 * ellipsis: ... : Consider complete dimensions up to the index
 * axis          : Synonymous for dimension (C style)
 * index  : lowering of dimensionality -> <b>always COPY</b>
 * slicing: preserves dimensionality   -> <b>always VIEW</b>

In [13]:
import numpy.random as rnd
rng = rnd.default_rng()
a = rng.random((3,4,5,6,7,6))
print(f"  a.shape:{a.shape}")
b = a[0:2,0:1]  # Slice in 2nd dim. ->  preserve dimensionality
print(f"  b.shape:{b.shape}") 
c = a[0:2,0]    # Index for 2nd dim. -> lowering dimensionality
print(f"  c.shape:{c.shape}")

  a.shape:(3, 4, 5, 6, 7, 6)
  b.shape:(2, 1, 5, 6, 7, 6)
  c.shape:(2, 5, 6, 7, 6)


### Slicing, indexing: view vs. copy ... CAN BE VERY DANGEROUS

#### Slicing

In [16]:
rng = rnd.default_rng()
a = rng.random((5,5))
print(f" a:\n{a}\n")

# B is a slice of A => VIEW
b = a[3:5,3:5]
print(f" b:\n{b}\n")
print(f" b.flags:\n{b.flags}\n")

#Modifying B:
b[:,:]=0.0
print(f" b:\n{b}\n")
print(f" a:\n{a}\n") #B IS A VIEW OF A, BUT IF YOU CHANGE B, YOU CHANGE A

 a:
[[0.39497185 0.39467205 0.58753657 0.61397652 0.97776728]
 [0.91837007 0.73277734 0.49117623 0.21988534 0.91249527]
 [0.18159628 0.39406269 0.49808624 0.13611065 0.40054219]
 [0.42165428 0.50325784 0.39881985 0.9017838  0.70316756]
 [0.30518907 0.12315186 0.73074078 0.16732842 0.86079582]]

 b:
[[0.9017838  0.70316756]
 [0.16732842 0.86079582]]

 b.flags:
  C_CONTIGUOUS : False
  F_CONTIGUOUS : False
  OWNDATA : False
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False


 b:
[[0. 0.]
 [0. 0.]]

 a:
[[0.39497185 0.39467205 0.58753657 0.61397652 0.97776728]
 [0.91837007 0.73277734 0.49117623 0.21988534 0.91249527]
 [0.18159628 0.39406269 0.49808624 0.13611065 0.40054219]
 [0.42165428 0.50325784 0.39881985 0.         0.        ]
 [0.30518907 0.12315186 0.73074078 0.         0.        ]]



#### Working on copy of a slice

In [17]:
rng = rnd.default_rng()
a = rng.random((5,5))
print(f" a:\n{a}\n")

# C is NOT a view BUT a copy
c = a[3:5,3:5].copy()
print(f" c:\n{c}\n")
print(f" c.flags:\n{c.flags}\n")

# Modifying C:
c[:,:] = -1.0
print(f" c:\n{c}\n")
print(f" a:\n{a}\n")

 a:
[[0.14511852 0.70275337 0.56865526 0.76645979 0.03553789]
 [0.73297569 0.41933575 0.61283872 0.43377865 0.78426342]
 [0.05394704 0.03785699 0.59518597 0.62637715 0.52611771]
 [0.26608797 0.61197496 0.82854987 0.27726805 0.18266897]
 [0.61474833 0.55071974 0.57899086 0.06819028 0.44348465]]

 c:
[[0.27726805 0.18266897]
 [0.06819028 0.44348465]]

 c.flags:
  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False


 c:
[[-1. -1.]
 [-1. -1.]]

 a:
[[0.14511852 0.70275337 0.56865526 0.76645979 0.03553789]
 [0.73297569 0.41933575 0.61283872 0.43377865 0.78426342]
 [0.05394704 0.03785699 0.59518597 0.62637715 0.52611771]
 [0.26608797 0.61197496 0.82854987 0.27726805 0.18266897]
 [0.61474833 0.55071974 0.57899086 0.06819028 0.44348465]]



#### Example of indexing

In [18]:
# D is obtained by pure indexing
rng = rnd.default_rng()
a = rng.random((5,5))
print(f" a:\n{a}\n")

d = a[1,2]
print(f" d:\n{d}\n")
print(f" d.flags:\n{d.flags}\n")

 a:
[[0.57062897 0.27873258 0.66364869 0.46116946 0.58319876]
 [0.39727464 0.33685288 0.04818057 0.17873137 0.58600259]
 [0.36450974 0.85954091 0.4205561  0.46383611 0.16179506]
 [0.60297224 0.64212216 0.12827943 0.29084815 0.48439353]
 [0.59069521 0.4425732  0.58312385 0.15561634 0.45743009]]

 d:
0.048180572111493625

 d.flags:
  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : False
  ALIGNED : True
  WRITEBACKIFCOPY : False




### What about reshaping? THIS TRIES TO AVOID COPYING

<i>From the Numpy manual</i>:<br>
It is <b>not always</b> possible to change the shape of an array without copying the data.


#### Example of reshaping without copying

In [19]:
# Default Memory layout is C
rng = rnd.default_rng()
x = rng.random((4,6))
print(f" x (Orig.):\n{x}\n")
print(f" x.flags:\n{x.flags}\n")
y=x.reshape((6,4))
print(f" x (After Reshaping):\n{y}\n")
print(f" x.flags:\n{y.flags}")

 x (Orig.):
[[0.50274536 0.54494148 0.41301954 0.10363977 0.37904033 0.90458993]
 [0.72606968 0.47297532 0.40923478 0.57471995 0.67537836 0.47088175]
 [0.18723036 0.22006276 0.77072248 0.17541586 0.640033   0.3976564 ]
 [0.97290597 0.25655586 0.34737966 0.72573777 0.1682953  0.55500423]]

 x.flags:
  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False


 x (After Reshaping):
[[0.50274536 0.54494148 0.41301954 0.10363977]
 [0.37904033 0.90458993 0.72606968 0.47297532]
 [0.40923478 0.57471995 0.67537836 0.47088175]
 [0.18723036 0.22006276 0.77072248 0.17541586]
 [0.640033   0.3976564  0.97290597 0.25655586]
 [0.34737966 0.72573777 0.1682953  0.55500423]]

 x.flags:
  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : False
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False



#### More problematic case

Note:<br>
We can create a view on an ndarray using the view method (vide infra)

In [20]:
# Create a rdn matrix A
rng = rnd.default_rng()
a = rng.random((4,6))
print(f" a:\n{a}\n")
print(f" a.flags:\n{a.flags}")

 a:
[[0.88550608 0.00784365 0.73102171 0.4399604  0.14555867 0.7222607 ]
 [0.76550077 0.09026784 0.3125669  0.57046402 0.0041406  0.68937368]
 [0.7001744  0.79215228 0.6419293  0.86015017 0.56893611 0.97724453]
 [0.03501813 0.81694633 0.5120587  0.45001934 0.81905904 0.51670102]]

 a.flags:
  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False



In [21]:
b = a.T
print(f" b:\n{b}\n")
print(f" b.flags:\n{b.flags}")

 b:
[[0.88550608 0.76550077 0.7001744  0.03501813]
 [0.00784365 0.09026784 0.79215228 0.81694633]
 [0.73102171 0.3125669  0.6419293  0.5120587 ]
 [0.4399604  0.57046402 0.86015017 0.45001934]
 [0.14555867 0.0041406  0.56893611 0.81905904]
 [0.7222607  0.68937368 0.97724453 0.51670102]]

 b.flags:
  C_CONTIGUOUS : False
  F_CONTIGUOUS : True
  OWNDATA : False
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False



In [22]:
# We FORCE to be a view on b
c = b.view()
print(f" c:\n{c}\n")
print(f" c.flags:\n{c.flags}")

 c:
[[0.88550608 0.76550077 0.7001744  0.03501813]
 [0.00784365 0.09026784 0.79215228 0.81694633]
 [0.73102171 0.3125669  0.6419293  0.5120587 ]
 [0.4399604  0.57046402 0.86015017 0.45001934]
 [0.14555867 0.0041406  0.56893611 0.81905904]
 [0.7222607  0.68937368 0.97724453 0.51670102]]

 c.flags:
  C_CONTIGUOUS : False
  F_CONTIGUOUS : True
  OWNDATA : False
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False



In [23]:
# Force c to reshape to a. 
# This requires a copy (can't because it is a VIEW) => Error
c.shape=(4,6)

AttributeError: Incompatible shape for in-place modification. Use `.reshape()` to make a copy with the desired shape.

## Exercises

* <b>Exercise 3.1</b>: 
  * Generate the following $2D$ matrix A:<br>
    $$\begin{bmatrix}
      1 & 2 & 3 & 4 & 5  & 6\\
      7 & 8 & 9 & 10 & 11 & 12\\ 
      13 & 14 & 15 & 16 & 17 & 18 \\
      19 & 20 & 21 & 22 & 23 & 24\\
      25 & 26 & 27 & 28 & 29 & 30
      \end{bmatrix}$$
  * Extract the following $2D$ matrix B from A:<br>
    $$\begin{bmatrix}
       1 & 3 \\
       7 & 9 \\
      13 & 15 \\
      19 & 21 \\
      25 & 27
      \end{bmatrix}$$
  * Extract the following $1D$ vector C from A:<br>
    $$\begin{bmatrix}
      8 & 10 & 12
      \end{bmatrix}$$ 
  * Could you extract the same object as a $2D$ matrix?  
  * Extract the following $2D$ matrix E from A:<br>
    $$\begin{bmatrix}
      2 & 5 \\
      20 & 23
      \end{bmatrix}$$
* <b>Exercise 3.2</b>:
  * Create a random matrix (7x7) with values $[0.0,1.0)$:<br>
    Replace the core 3x3 matrix of the above matrix with ones.<br>
    (Hint: use the np.random.random function to create the matrix)
* <b>Exercise 3.3</b>:
  * Create the following (8x8) checkerboard containing 0 and 1's (type integer) in 2 different ways:
    $$\begin{bmatrix}
      0 & 1 & 0 & 1 &  0 & 1 & 0 & 1\\
      1 & 0 & 1 &  0 & 1 & 0 & 1 & 0\\
      0 & 1 & 0 & 1 &  0 & 1 & 0 & 1\\
      1 & 0 & 1 &  0 & 1 & 0 & 1 & 0\\
      0 & 1 & 0 & 1 &  0 & 1 & 0 & 1\\
      1 & 0 & 1 &  0 & 1 & 0 & 1 & 0\\
      0 & 1 & 0 & 1 &  0 & 1 & 0 & 1 \\
      1 & 0 & 1 &  0 & 1 & 0 & 1 & 0
      \end{bmatrix}$$
    * ONLY using slicing
    * using the numpy np.tile function (use help to find the syntax)

## Solutions

In [3]:
# %load ../solutions/ex3.py
#exercise 3.1
A = np.arange(1,31).reshape((5,6))
print(A)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]]


In [6]:
A[:,0:3:2]

array([[ 1,  3],
       [ 7,  9],
       [13, 15],
       [19, 21],
       [25, 27]])

In [7]:
A[1,1::2]

array([ 8, 10, 12])

In [8]:
A[1:2,1::2]

array([[ 8, 10, 12]])

In [13]:
A[0::3,1::3]

array([[ 2,  5],
       [20, 23]])